# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-02 13:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0027_auto_20161130_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='choice',
            field=models.CharField(choices=[('like', 'like'), ('dislike', 'dislike'), ('normal', 'normal')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='article',
            name='voter',
            field=models.ManyToManyField(to='firstapp.UserProfile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateField(default=datetime.datetime(2017, 2, 2, 13, 22, 58, 330352)),
        ),
    ]
