# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-02 14:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0030_auto_20170202_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='article',
            name='voter',
        ),
        migrations.AddField(
            model_name='tag',
            name='tag',
            field=models.CharField(blank=True, choices=[('dxs', '大学生'), ('lnr', '老年人'), ('信用卡', '信用卡'), ('扫二维码', '扫二维码'), ('短信', '短信')], max_length=5, null=True),
        ),
        migrations.RemoveField(
            model_name='article',
            name='tag',
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(to='firstapp.Tag'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateField(default=datetime.datetime(2017, 2, 2, 14, 43, 2, 108202)),
        ),
    ]
