# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-02 15:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0032_auto_20170202_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tag',
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateField(default=datetime.datetime(2017, 2, 2, 15, 22, 11, 751345)),
        ),
    ]
