# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-03 16:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0033_auto_20170202_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ilike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('like', 'like'), ('normal', 'normal')], max_length=10)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilike', to='firstapp.Article')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_ilike', to='firstapp.UserProfile')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateField(default=datetime.datetime(2017, 2, 3, 16, 20, 10, 164131)),
        ),
    ]
