# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 02:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0037_auto_20170205_0602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idontlike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateField(default=datetime.datetime(2017, 3, 2, 2, 19, 5, 117964)),
        ),
    ]
